

CREATE TABLE rawLoanDates(
    asOfDate DATETIME PRIMARY KEY
);


CREATE TABLE loansFundedAsOfDate(
    asOfDate DATETIME REFERENCES rawLoanDates(asOfDate),
    fundedAmount REAL,
    id INTEGER REFERENCES rawLoans(id)
);


CREATE TABLE rawLoans(
    acceptD INTEGER,
    accNowDelinq INTEGER,
    accOpenPast24Mths INTEGER,
    addrState VARCHAR(64),
    addrZip VARCHAR(3),
    annualInc REAL,
    avgCurBal INTEGER,
    bcOpenToBuy INTEGER,
    bcUtil REAL,
    chargeoffWithin12Mths INTEGER,
    collections12MthsExMed INTEGER,
    creditPullD INTEGER,
    delinq2Yrs INTEGER,
    delinqAmnt REAL,
    desc TEXT,
    dti REAL,
    earliestCrLine INTEGER,
    empLength INTEGER,
    empTitle VARCHAR(64),
    expD INTEGER,
    expDefaultRate REAL,
    ficoRangeHigh INTEGER,
    ficoRangeLow INTEGER,
    grade CHARACTER(1),
    homeOwnership VARCHAR(16),
    id INTEGER PRIMARY KEY,
    ilsExpD INTEGER,
    initialListStatus CHARACTER(1),
    inqLast6Mths INTEGER,
    installment REAL,
    intRate REAL,
    investorCount INTEGER,
    isIncV VARCHAR(16),
    listD INTEGER,
    loanAmount REAL,
    memberId INTEGER,
    mortAcc INTEGER,
    moSinOldIlAcct INTEGER,
    moSinOldRevTlOp INTEGER,
    moSinRcntRevTlOp INTEGER,
    moSinRcntTl INTEGER,
    mthsSinceLastDelinq INTEGER,
    mthsSinceLastMajorDerog INTEGER,
    mthsSinceLastRecord INTEGER,
    mthsSinceRecentBc INTEGER,
    mthsSinceRecentBcDlq INTEGER,
    mthsSinceRecentInq INTEGER,
    mthsSinceRecentRevolDelinq INTEGER,
    numAcctsEver120Ppd INTEGER,
    numActvBcTl INTEGER,
    numActvRevTl INTEGER,
    numBcSats INTEGER,
    numBcTl INTEGER,
    numIlTl INTEGER,
    numOpRevTl INTEGER,
    numRevAccts INTEGER,
    numRevTlBalGt0 INTEGER,
    numSats INTEGER,
    numTl120dpd2m INTEGER,
    numTl30dpd INTEGER,
    numTl90gDpd24m INTEGER,
    numTlOpPast12m INTEGER,
    openAcc INTEGER,
    pctTlNvrDlq INTEGER,
    percentBcGt75 REAL,
    pubRec INTEGER,
    pubRecBankruptcies INTEGER,
    purpose VARCHAR(32),
    reviewStatus VARCHAR(16),
    reviewStatusD INTEGER,
    revolBal REAL,
    revolUtil REAL,
    serviceFeeRate REAL,
    subGrade CHARACTER(2),
    taxLiens INTEGER,
    term INTEGER,
    totalAcc INTEGER,
    totalBalExMort INTEGER,
    totalBcLimit INTEGER,
    totalIlHighCreditLimit INTEGER,
    totalRevHiLim INTEGER,
    totCollAmt INTEGER,
    totCurBal INTEGER,
    totHiCredLim INTEGER
);
